### ISSUE TITLE
Update API Endpoint Naming to Use Kebab-Case

### ISSUE THREAD

**Issue by Sirmelihy** [Rater-Inc/dotnet-api#30]
**Issue Description**

- Currently, our API endpoints are named using camelCase. To improve readability and adhere to common RESTful API naming conventions, we should update our endpoint names to use kebab-case.

**Expected Change**

- Update all current API endpoints from camelCase to kebab-case.
- Ensure that all internal and external documentation is updated to reflect this change.

**Benefits**

- Improves consistency with widespread RESTful practices.
- Enhances readability for especially front-end developers.
- Ensures compatibility with tools that may expect kebab-case naming conventions.

**Comment by rknyryn** [comment]
Hello, you can check out this document ([link](https://github.com/ktaranov/naming-convention/blob/master/C%23%20Coding%20Standards%20and%20Naming%20Conventions.md)) for C# naming convention.
